---
abstract: 'Indented output for Tags.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.01
  IO::Scalar: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-Output-Indent
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.05
  Indent: 0.01
  Indent::Block: 0.01
  Indent::Word: 0.01
  List::MoreUtils: 0
  Readonly: 0
  Tags::Output: 0.1
  Tags::Utils: 0.09
  Tags::Utils::Preserve: 0.09
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Tags-Output-Indent/issues
  homepage: https://github.com/michal-josef-spacek/Tags-Output-Indent
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-Output-Indent
version: '0.10'
